---
title: "Tutorial: How to Use kwb.resilience"
author: "Andreas Matzinger"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Tutorial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 7, 
  fig.height = 5
)
```

## Install kwb.resilience from GitHub

```{r eval = FALSE}
# install.packages("devtools")

devtools::install_github("kwb-r/kwb.resilience", dependencies = TRUE)
```

## Load the package

```{r}
library("kwb.resilience")
```

### Define Helper Functions

```{r}
plot_dissolved_oxygen_S4 <- function(oxygen, ...) {
  plot(
    x = oxygen$timestamp, 
    y = oxygen$S4_red_Imp_Surface, 
    xlab = "Time", 
    ylab = "DO in mg/l",
    ...
  )
}
```

### Example Data

Let's have a look at some example data:

```{r}
# Show the first lines of the example data
head(oxygen)

# Plot the example data
plot_dissolved_oxygen_S4(oxygen)
```

### Severity and Resilience

Example for scenario 4:

```{r}
system.time(Sev.S4 <- resilience.severity(
  time_stamp = oxygen$timestamp, 
  Pt = oxygen$S4_red_Imp_Surface, 
  Pa = 2, 
  Pmax = 0
))

# Use another method of integral calculation (loop -> vector calculation)
system.time(Sev.S4.control <- resilience.severity(
  time_stamp = oxygen$timestamp, 
  Pt = oxygen$S4_red_Imp_Surface, 
  Pa = 2, 
  Pmax = 0,
  integral_method = 2
))

# Method 2 should be faster but both methods should return the same!
stopifnot(identical(Sev.S4, Sev.S4.control))

Res0.S4 <- 1 - Sev.S4
```

### Resilience Indices Separate for Each Event 

Example for scenario 4:

```{r}
# Define the acceptable performance
Pa <- 2

# Calculate Events
events.S4 <- resilience.events(
  time_stamp = oxygen$timestamp, 
  Pt = oxygen$S4_red_Imp_Surface, 
  Pa = Pa, 
  Pmax = 0, 
  evtSepTime = 6 * 60 * 60, 
  signalWidth = 15 * 60
)

# Plot Events
for (i in seq_len(nrow(events.S4))) {
  
  event <- events.S4[i, ]
  
  xlim <- kwb.utils::extendLimits(kwb.event::eventToXLim(event), 5)
  
  plot_dissolved_oxygen_S4(oxygen, xlim = xlim, main = paste("Event", i))
  
  abline(v = unlist(event[, c("tBeg", "tEnd")]), col = "grey")
  
  abline(h = Pa, col = "red")
}
```

### Summary

```{r}
resi.summary <- resilience.summary(
  time_stamp = oxygen$timestamp, 
  Pt = oxygen[, setdiff(names(oxygen), "timestamp")], 
  Pa = 2, 
  Pmax = 0, 
  evtSepTime = 6 * 60 * 60, 
  signalWidth = 15 * 60
)

resi.summary
```
