#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("resilience.summary() works", {

  
    kwb.resilience:::resilience.summary(
      time_stamp = oxygen$timestamp, 
      Pt = oxygen[, setdiff(names(oxygen), "timestamp")], 
      Pa = 2, 
      Pmax = 0, 
      evtSepTime = 6 * 60 * 60, 
      signalWidth = 15 * 60
    )


})

