#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("resilience.summary() works", {

  expect_error(
    kwb.resilience:::resilience.summary()
    # argument "Pt" is missing, with no default
  )

})

