#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("resilience.severity() works", {

    kwb.resilience:::resilience.severity(time_stamp = oxygen$timestamp, 
                                          Pt = oxygen$S4_red_Imp_Surface, 
                                          Pa = 2, 
                                          Pmax = 0)

})

