#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("resilience.events() works", {

  expect_error(
    kwb.resilience:::resilience.events()
    # argument "time_stamp" is missing, with no default
  )

})

