#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("resilience.severity() works", {

  expect_error(
    kwb.resilience:::resilience.severity()
    # argument "time_stamp" is missing, with no default
  )

})

