#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("resilience.events() works", {


    kwb.resilience:::resilience.events(time_stamp = oxygen$timestamp, 
                                       Pt = oxygen$S4_red_Imp_Surface, 
                                       Pa = 2, 
                                       Pmax = 0, 
                                       evtSepTime = 6 * 60 * 60, 
                                       signalWidth = 15 * 60)


})

